language: python
python:
  - "2.7"

# set environment variables
env:
    - DJANGO_SETTINGS_MODULE="harvardcards.settings.dev"

# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"

# command(s) to run before main script
before_script: 
    - mkdir -p logs 
    - touch logs/app.log
    
# command(s) to run tests
script: 
    - python manage.py syncdb --noinput
    - python manage.py migrate --noinput
    - nosetests
