language: python
python:
  - "2.7"

# set environment variables
env:
    - DJANGO_SETTINGS_MODULE="harvardcards.settings.dev"

# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"

# command to run tests
script: nosetests
