application: dev-harvardcards
version: 1
runtime: python27
api_version: 1
threadsafe: true

env_variables:
  DJANGO_SETTINGS_MODULE: 'harvardcards.settings.googleappengine'

libraries:
- name: django
  version: "1.5"

builtins:
- django_wsgi: on

handlers:
- url: /static
  static_dir: harvardcards/static
  expiration: '0'
