# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 16:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stmt_id', models.CharField(max_length=36)),
                ('stmt_actor_desc', models.CharField(max_length=4000)),
                ('stmt_verb', models.CharField(max_length=4000)),
                ('stmt_object', models.CharField(max_length=4000)),
                ('stmt_context', models.TextField(blank=True)),
                ('stmt_timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('stmt_stored', models.DateTimeField(auto_now_add=True)),
                ('stmt_json', models.TextField(blank=True)),
                ('stmt_actor_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-stmt_stored', 'stmt_actor_user', 'stmt_actor_desc', 'stmt_verb', 'stmt_object'],
                'verbose_name': 'Analytics',
                'verbose_name_plural': 'Analytics',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('color', models.CharField(choices=[(b'default', b'Default'), (b'blue', b'Blue'), (b'pink', b'Pink'), (b'green', b'Green'), (b'orange', b'Orange'), (b'white', b'White')], default=b'default', max_length=12)),
                ('clone_ref_id', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cards_Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('clone_ref_id', models.CharField(max_length=50, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flash.Card')),
            ],
            options={
                'ordering': ['field__sort_order'],
                'verbose_name': 'Card Fields',
                'verbose_name_plural': 'Card Fields',
            },
        ),
        migrations.CreateModel(
            name='CardTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardTemplates_Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flash.CardTemplate')),
            ],
            options={
                'ordering': ['field__sort_order'],
                'verbose_name': 'Card Template Fields',
                'verbose_name_plural': 'Card Template Fields',
            },
        ),
        migrations.CreateModel(
            name='Clone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clone_date', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(max_length=48)),
                ('model_id', models.CharField(max_length=24)),
                ('status', models.CharField(choices=[(b'Q', b'QUEUED'), (b'P', b'PROCESSING'), (b'D', b'DONE')], max_length=1)),
                ('cloned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-clone_date', 'model', 'model_id', 'cloned_by'],
                'verbose_name': 'Clone',
                'verbose_name_plural': 'Clones',
            },
        ),
        migrations.CreateModel(
            name='Cloned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=48)),
                ('old_model_id', models.CharField(max_length=24)),
                ('new_model_id', models.CharField(max_length=24)),
                ('clone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flash.Clone')),
            ],
            options={
                'ordering': ['-clone', 'model', 'old_model_id', 'new_model_id'],
                'verbose_name': 'Cloned',
                'verbose_name_plural': 'Cloned',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('card_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flash.CardTemplate')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_course_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('course_id', models.CharField(max_length=255, unique=True)),
                ('entity', models.CharField(max_length=255)),
                ('context_id', models.CharField(max_length=255)),
                ('course_name_short', models.CharField(max_length=1024)),
                ('course_name', models.CharField(max_length=2048)),
            ],
            options={
                'ordering': ['course_id', 'course_name_short', 'course_name'],
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses ',
            },
        ),
        migrations.CreateModel(
            name='Course_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flash.Collection')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flash.Course')),
            ],
            options={
                'ordering': ['course', 'collection__id', 'subscribe'],
                'verbose_name': 'Course Map',
                'verbose_name_plural': 'Course Maps',
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=1)),
                ('clone_ref_id', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'verbose_name': 'Deck',
                'verbose_name_plural': 'Decks',
            },
        ),
        migrations.CreateModel(
            name='Decks_Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=1)),
                ('clone_ref_id', models.CharField(max_length=50, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flash.Card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flash.Deck')),
            ],
            options={
                'ordering': ['sort_order'],
                'verbose_name': 'Deck Cards',
                'verbose_name_plural': 'Deck Cards',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('field_type', models.CharField(choices=[(b'T', b'Text'), (b'I', b'Image'), (b'A', b'Audio'), (b'V', b'Video'), (b'M', b'Math')], max_length=1)),
                ('show_label', models.BooleanField()),
                ('display', models.BooleanField()),
                ('sort_order', models.IntegerField(default=1)),
                ('example_value', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['sort_order'],
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
            },
        ),
        migrations.CreateModel(
            name='MediaStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=1024)),
                ('file_size', models.PositiveIntegerField()),
                ('file_type', models.CharField(max_length=127)),
                ('file_md5hash', models.CharField(max_length=32)),
                ('store_created', models.DateTimeField(auto_now_add=True)),
                ('store_updated', models.DateTimeField(auto_now=True)),
                ('reference_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['file_name'],
                'verbose_name': 'Media Store',
                'verbose_name_plural': 'Media Stores',
            },
        ),
        migrations.CreateModel(
            name='Users_Collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('role', models.CharField(choices=[(b'O', b'Observer'), (b'L', b'Learner'), (b'T', b'Teaching Assistant'), (b'C', b'Content Developer'), (b'I', b'Instructor'), (b'A', b'Administrator')], default=b'O', max_length=1)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flash.Collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Users Collections',
                'verbose_name_plural': 'Users Collections',
            },
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(through='flash.Decks_Cards', to='flash.Card'),
        ),
        migrations.AddField(
            model_name='deck',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flash.Collection'),
        ),
        migrations.AddField(
            model_name='collection',
            name='users',
            field=models.ManyToManyField(through='flash.Users_Collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardtemplates_fields',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flash.Field'),
        ),
        migrations.AddField(
            model_name='cardtemplate',
            name='fields',
            field=models.ManyToManyField(through='flash.CardTemplates_Fields', to='flash.Field'),
        ),
        migrations.AddField(
            model_name='cardtemplate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cards_fields',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flash.Field'),
        ),
        migrations.AddField(
            model_name='card',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flash.Collection'),
        ),
        migrations.AddField(
            model_name='card',
            name='fields',
            field=models.ManyToManyField(through='flash.Cards_Fields', to='flash.Field'),
        ),
    ]
